config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  resources :student_groups
  resources :classrooms
  resources :subjects
  resources :schools
  resources :lessons
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "home_page#index"
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_and_belongs_to_many :classrooms
  has_many :lessons
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  def index
    @subjects = Subject.all
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to @subject, notice: "Subject was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
      if @subject.update(subject_params)
        redirect_to @subject, notice: "Subject was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @subject.destroy!

    redirect_to subjects_path, status: :see_other, notice: "Subject was successfully destroyed."
  end

  private
    def set_subject
      @subject = Subject.find(params[:id])
    end

    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, class: "contents") do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= subject.name %>
  </p>

</div>

app/views/subjects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing subject</h1>

  <%= render "form", subject: @subject %>

  <%= link_to "Show this subject", @subject, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to subjects", subjects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subjects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Subjects" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Subjects</h1>
    <% if current_user.admin? %>
      <%= link_to "New subject", new_subject_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="subjects" class="min-w-full">
    <% @subjects.each do |subject| %>
      <div class="lesson-item bg-white shadow-md rounded-lg p-4 mb-4 transition-transform transform hover:scale-105">
        <h2 class="text-lg font-semibold text-blue-800"><%= subject.name %></h2>
        <p>
          <%= link_to "Show this subject", subject, class: "mt-2 rounded-lg py-2 px-4 bg-blue-600 text-white inline-block font-medium" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New subject</h1>

  <%= render "form", subject: @subject %>

  <%= link_to "Back to subjects", subjects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subjects/show.html.erb
<div class="flex items-center justify-center min-h-screen">
  <div class="bg-white shadow-lg rounded-lg p-6 md:w-2/3 w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-xl inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="mb-4">
      <h2 class="text-2xl font-bold text-gray-800 mb-2"><%= @subject.name %></h2>
    </div>

    <div class="flex justify-between mt-4">
      <%= link_to "Back to subjects", subjects_path, class: "rounded-lg py-2 px-4 bg-gray-300 text-gray-800 font-medium hover:bg-gray-400 transition" %>

      <% if current_user.teacher? || current_user.admin? %>
        <div class="flex space-x-2">
          <%= link_to "Edit this subject", edit_subject_path(@subject), class: "rounded-lg py-2 px-4 bg-blue-600 text-white font-medium hover:bg-blue-700 transition" %>
          <%= button_to "Destroy this subject", @subject, method: :delete, class: "rounded-lg py-2 px-4 bg-red-600 text-white font-medium hover:bg-red-700 transition" %>
        </div>
      <% end %>
    </div>
  </div>
</div>