config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  resources :student_groups
  resources :classrooms
  resources :subjects
  resources :schools
  resources :lessons
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "home_page#index"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student_group
  belongs_to :user
  belongs_to :classroom
  belongs_to :subject
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  def index
    @lessons = Lesson.where("start_time < ?", Date.beginning_of_week)
    @lessons_today = @lessons.where(start_time: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)

    if @lesson.save
      redirect_to @lesson, notice: "Lesson was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @lesson.update(lesson_params)
      redirect_to @lesson, notice: "Lesson was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @lesson.destroy!

    redirect_to lessons_path, status: :see_other, notice: "Lesson was successfully destroyed."
  end

  private
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :description, :start_time, :end_time, :student_group_id, :user_id, :classroom_id, :subject_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, class: "contents") do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_time %>
    <%= form.datetime_field :start_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end_time %>
    <%= form.datetime_field :end_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :student_group_id %>
    <%= form.collection_select :student_group_id, StudentGroup.all, :id, :name, { prompt: "Select a student group" }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :name, { prompt: "Select a teacher" }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :classroom_id %>
    <%= form.collection_select :classroom_id, Classroom.all, :id, :name, { prompt: "Select a classroom" }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :subject_id %>
    <%= form.collection_select :subject_id, Subject.all, :id, :name, { prompt: "Select a subject" }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p> <%= lesson.title %>
  <p> <%= lesson.description%>
</div>

app/views/lessons/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Show this lesson", @lesson, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lessons/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="w-96 flex flex-row">
    <%= week_calendar(number_of_weeks: 1, events: @lessons) do |date, lessons| %>
      <div class="date-header text-sm font-semibold mb-2 text-center">
        <%= date.strftime("%b %d") %>
      </div>

      <div class="lessons-container space-y-2 h-max w-48 px-2">
        <% if lessons.any? %>
          <% lessons.each do |lesson| %>
            <%= link_to lesson, class: "lesson-item block p-2 rounded-lg bg-blue-100 hover:bg-blue-200 transition duration-300" do %>
              <div class="text-blue-800 font-medium"><%= lesson.title %></div>
              <div class="text-xs text-blue-600"><%= lesson.start_time.strftime("%I:%M %p") %></div>
            <% end %>
          <% end %>
        <% else %>
          <div class="text-center text-gray-500 italic">No lessons</div>
        <% end %>
      </div>
    <% end %>
  </div>

  </br>
  <% content_for :title, "Lessons" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lessons today</h1>
    <% if current_user.teacher? || current_user.admin?%>
      <%= link_to "New lesson", new_lesson_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="lessons" class="min-w-full">
    <% @lessons_today.each do |lesson| %>
      <div class="lesson-item bg-white shadow-md rounded-lg p-4 mb-4 transition-transform transform hover:scale-105">
        <h2 class="text-lg font-semibold text-blue-800"><%= lesson.title %></h2>
        <p class="text-gray-600"><%= lesson.description %></p>
        <p class="text-sm text-gray-500">
          Start Time: <%= lesson.start_time.strftime("%I:%M %p") %> | 
          End Time: <%= lesson.end_time.strftime("%I:%M %p") %>
        </p>
        <p>
          <%= link_to "Show this lesson", lesson, class: "mt-2 rounded-lg py-2 px-4 bg-blue-600 text-white inline-block font-medium" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lessons/show.html.erb
<div class="flex items-center justify-center min-h-screen">
  <div class="bg-white shadow-lg rounded-lg p-6 md:w-2/3 w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-xl inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="mb-4">
      <h2 class="text-2xl font-bold text-gray-800 mb-2"><%= @lesson.title %></h2>
      <p class="text-gray-600"><%= @lesson.description %></p>
      <p class="text-sm text-gray-500"><%= "#{@lesson.start_time.strftime("%I:%M %p")} - #{ @lesson.end_time.strftime("%I:%M %p")}" %></p>
      <p class="text-sm text-gray-500"><%= "#{@lesson.user.name} #{@lesson.user.surname}" if @lesson.user %></p>
      <p class="text-sm text-gray-500"><%= @lesson.classroom.name if @lesson.classroom %></p>
    </div>

    <div class="flex justify-between mt-4">
      <%= link_to "Back to lessons", lessons_path, class: "rounded-lg py-2 px-4 bg-gray-300 text-gray-800 font-medium hover:bg-gray-400 transition" %>

      <% if current_user.teacher? || current_user.admin? %>
        <div class="flex space-x-2">
          <%= link_to "Edit this lesson", edit_lesson_path(@lesson), class: "rounded-lg py-2 px-4 bg-blue-600 text-white font-medium hover:bg-blue-700 transition" %>
          <%= button_to "Destroy this lesson", @lesson, method: :delete, class: "rounded-lg py-2 px-4 bg-red-600 text-white font-medium hover:bg-red-700 transition" %>
        </div>
      <% end %>
    </div>
  </div>
</div>