config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  resources :student_groups
  resources :classrooms
  resources :subjects
  resources :schools
  resources :lessons
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "home_page#index"
end

app/models/school.rb
class School < ApplicationRecord
  has_many :classrooms
  has_many :users
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[ show edit update destroy ]

  def index
    @schools = School.all
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to @school, notice: "School was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @school.update(school_params)
      redirect_to @school, notice: "School was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @school.destroy!

    redirect_to schools_path, status: :see_other, notice: "School was successfully destroyed."
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(:name, :localization, :description)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, class: "contents") do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :localization %>
    <%= form.text_area :localization, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/schools/_school.html.erb
<div id="<%= dom_id school %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= school.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Localization:</strong>
    <%= school.localization %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= school.description %>
  </p>

</div>

app/views/schools/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing school</h1>

  <%= render "form", school: @school %>

  <%= link_to "Show this school", @school, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to schools", schools_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/schools/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Schools" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Schools</h1>
    <% if current_user.admin?%>
      <%= link_to "New school", new_school_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="schools" class="min-w-full">
    <% @schools.each do |school| %>
      <div class="lesson-item bg-white shadow-md rounded-lg p-4 mb-4 transition-transform transform hover:scale-105">
        <h2 class="text-lg font-semibold text-blue-800"><%= school.name %></h2>
        <p class="text-gray-600"><%= school.localization %></p>
        <p class="text-gray-600"><%= school.description %></p>
        <p>
          <%= link_to "Show this school", school, class: "mt-2 rounded-lg py-2 px-4 bg-blue-600 text-white inline-block font-medium" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/schools/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New school</h1>

  <%= render "form", school: @school %>

  <%= link_to "Back to schools", schools_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/schools/show.html.erb
<div class="flex items-center justify-center min-h-screen">
  <div class="bg-white shadow-lg rounded-lg p-6 md:w-2/3 w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-xl inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="mb-4">
      <h2 class="text-2xl font-bold text-gray-800 mb-2"><%= @school.name %></h2>
      <p class="text-gray-600"><%= @school.localization %></p>
      <p class="text-sm text-gray-500"><%= @school.description %></p>
    </div>

    <div class="flex justify-between mt-4">
      <%= link_to "Back to schools", schools_path, class: "rounded-lg py-2 px-4 bg-gray-300 text-gray-800 font-medium hover:bg-gray-400 transition" %>

      <% if current_user.teacher? || current_user.admin? %>
        <div class="flex space-x-2">
          <%= link_to "Edit this school", edit_school_path(@school), class: "rounded-lg py-2 px-4 bg-blue-600 text-white font-medium hover:bg-blue-700 transition" %>
          <%= button_to "Destroy this school", @school, method: :delete, class: "rounded-lg py-2 px-4 bg-red-600 text-white font-medium hover:bg-red-700 transition" %>
        </div>
      <% end %>
    </div>
  </div>
</div>